export const MISSIONS = [
  'pretend to be on your phone and get another player to write down a number for you',
  'get a movie quote wrong and get another player to correct you',
  "call a player and pretend to be someone selling something. get them to hang up without realizing it's you",
  'get a player to try and cure your hiccups',
  'get a player to make an animal noise',
  'ask a player to message you later to remind you to do something. if they message you, reply with a screenshot of this card',
  'get a player to say game over',
  'count to three in another language. if another player keeps counting after you finished, mission accomplished',
  'get a player to hit you',
  'throw a paper airplane at a player and get them to throw it back at you',
  'suggest a song and get another player to play it on their phone',
  'get a player to make a deer noise by telling them that deer dont make noises',
  'get a player to play rock, paper, scissors with you until you win',
  'make up a fake product and tell a player that they would love it and get them to search for it on the internet',
  'get a player to read out a sentence from a book',
  'get a player to compliment your hair',
  'get the words to a song slightly wrong and get another player to correct you',
  'get a player to correct you on the time of day',
  'tell a player they have something on their face, get them to look in a mirror',
  'get a player to tell you their age',
  'tie a players shoes together while they are wearing them without being caught',
  'balance a bunch of objects on top of each other and get another player to knock it over',
  'claim you saw someone famous the other day who is dead. get a player to call you out on it',
  'get a player to draw something on your skin',
  'get a player to tell you that you have dropped something',
  'get a player to give you a hug',

]